package com.idcq.appserver.dto.message;

import java.io.Serializable;
import java.util.Date;

public class MessageCenterDto implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5009373680942866491L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.message_id
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Long messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.handle_type
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Integer handleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.client_system_type
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Integer clientSystemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.message_title
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private String messageTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.show_content
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private String showContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.message_image
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private String messageImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.json_data
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private String jsonData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.notify_type
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Integer notifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.receiver_id
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Long receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.notify_time
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Date notifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.notify_channel
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Integer notifyChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.biz_type
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Integer bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.biz_id
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Long bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.message_status
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Integer messageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.notify_model
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Integer notifyModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.expect_send_time
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Date expectSendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.send_result
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Integer sendResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.repeat_times
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Integer repeatTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_message_center.feedback_type
     *
     * @mbggenerated Sat Mar 12 12:11:08 CST 2016
     */
    private Integer feedbackType;

	public MessageCenterDto() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Long getMessageId() {
		return messageId;
	}

	public void setMessageId(Long messageId) {
		this.messageId = messageId;
	}

	public Integer getHandleType() {
		return handleType;
	}

	public void setHandleType(Integer handleType) {
		this.handleType = handleType;
	}

	public Integer getClientSystemType() {
		return clientSystemType;
	}

	public void setClientSystemType(Integer clientSystemType) {
		this.clientSystemType = clientSystemType;
	}

	public String getMessageTitle() {
		return messageTitle;
	}

	public void setMessageTitle(String messageTitle) {
		this.messageTitle = messageTitle;
	}

	public String getShowContent() {
		return showContent;
	}

	public void setShowContent(String showContent) {
		this.showContent = showContent;
	}

	public String getMessageImage() {
		return messageImage;
	}

	public void setMessageImage(String messageImage) {
		this.messageImage = messageImage;
	}

	public String getJsonData() {
		return jsonData;
	}

	public void setJsonData(String jsonData) {
		this.jsonData = jsonData;
	}

	public Integer getNotifyType() {
		return notifyType;
	}

	public void setNotifyType(Integer notifyType) {
		this.notifyType = notifyType;
	}

	public Long getReceiverId() {
		return receiverId;
	}

	public void setReceiverId(Long receiverId) {
		this.receiverId = receiverId;
	}

	public Date getNotifyTime() {
		return notifyTime;
	}

	public void setNotifyTime(Date notifyTime) {
		this.notifyTime = notifyTime;
	}

	public Integer getNotifyChannel() {
		return notifyChannel;
	}

	public void setNotifyChannel(Integer notifyChannel) {
		this.notifyChannel = notifyChannel;
	}

	public Integer getBizType() {
		return bizType;
	}

	public void setBizType(Integer bizType) {
		this.bizType = bizType;
	}

	public Long getBizId() {
		return bizId;
	}

	public void setBizId(Long bizId) {
		this.bizId = bizId;
	}

	public Integer getMessageStatus() {
		return messageStatus;
	}

	public void setMessageStatus(Integer messageStatus) {
		this.messageStatus = messageStatus;
	}

	public Integer getNotifyModel() {
		return notifyModel;
	}

	public void setNotifyModel(Integer notifyModel) {
		this.notifyModel = notifyModel;
	}

	public Date getExpectSendTime() {
		return expectSendTime;
	}

	public void setExpectSendTime(Date expectSendTime) {
		this.expectSendTime = expectSendTime;
	}

	public Integer getSendResult() {
		return sendResult;
	}

	public void setSendResult(Integer sendResult) {
		this.sendResult = sendResult;
	}

	public Integer getRepeatTimes() {
		return repeatTimes;
	}

	public void setRepeatTimes(Integer repeatTimes) {
		this.repeatTimes = repeatTimes;
	}

	public Integer getFeedbackType() {
		return feedbackType;
	}

	public void setFeedbackType(Integer feedbackType) {
		this.feedbackType = feedbackType;
	}

	@Override
	public String toString() {
		return "MessageCenterDto [messageId=" + messageId + ", handleType="
				+ handleType + ", clientSystemType=" + clientSystemType
				+ ", messageTitle=" + messageTitle + ", showContent="
				+ showContent + ", messageImage=" + messageImage
				+ ", jsonData=" + jsonData + ", notifyType=" + notifyType
				+ ", receiverId=" + receiverId + ", notifyTime=" + notifyTime
				+ ", notifyChannel=" + notifyChannel + ", bizType=" + bizType
				+ ", bizId=" + bizId + ", messageStatus=" + messageStatus
				+ ", notifyModel=" + notifyModel + ", expectSendTime="
				+ expectSendTime + ", sendResult=" + sendResult
				+ ", repeatTimes=" + repeatTimes + ", feedbackType="
				+ feedbackType + "]";
	}
    
    

}