package com.idcq.appserver.dto.programconfig;

import java.io.Serializable;

public class ExecuteDetailDto implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -7647750971513784699L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_detail.execute_point_id
     *
     * @mbggenerated Mon Mar 14 19:56:53 CST 2016
     */
    private Integer executePointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_detail.program_config_id
     *
     * @mbggenerated Mon Mar 14 19:56:53 CST 2016
     */
    private Integer programConfigId;

	public ExecuteDetailDto() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Integer getExecutePointId() {
		return executePointId;
	}

	public void setExecutePointId(Integer executePointId) {
		this.executePointId = executePointId;
	}

	public Integer getProgramConfigId() {
		return programConfigId;
	}

	public void setProgramConfigId(Integer programConfigId) {
		this.programConfigId = programConfigId;
	}
    
    

}