package com.idcq.appserver.dto.programconfig;

import java.io.Serializable;

public class ExecutePointDto implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 7914419783477199983L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.execute_point_id
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private Integer executePointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.code
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.config_id
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private Integer configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.implement_interface
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private String implementInterface;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.module_code
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private String moduleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.point_name
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.point_desc
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private String pointDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.point_type
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private Integer pointType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.point_execute_type
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private Integer pointExecuteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.biz_id
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private Long bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_execute_point.biz_type
     *
     * @mbggenerated Mon Mar 14 19:42:21 CST 2016
     */
    private Integer bizType;
    
	public ExecutePointDto() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Integer getExecutePointId() {
		return executePointId;
	}

	public void setExecutePointId(Integer executePointId) {
		this.executePointId = executePointId;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Integer getConfigId() {
		return configId;
	}

	public void setConfigId(Integer configId) {
		this.configId = configId;
	}

	public String getImplementInterface() {
		return implementInterface;
	}

	public void setImplementInterface(String implementInterface) {
		this.implementInterface = implementInterface;
	}

	public String getModuleCode() {
		return moduleCode;
	}

	public void setModuleCode(String moduleCode) {
		this.moduleCode = moduleCode;
	}

	public String getPointName() {
		return pointName;
	}

	public void setPointName(String pointName) {
		this.pointName = pointName;
	}

	public String getPointDesc() {
		return pointDesc;
	}

	public void setPointDesc(String pointDesc) {
		this.pointDesc = pointDesc;
	}

	public Integer getPointType() {
		return pointType;
	}

	public void setPointType(Integer pointType) {
		this.pointType = pointType;
	}

	public Integer getPointExecuteType() {
		return pointExecuteType;
	}

	public void setPointExecuteType(Integer pointExecuteType) {
		this.pointExecuteType = pointExecuteType;
	}

	public Long getBizId() {
		return bizId;
	}

	public void setBizId(Long bizId) {
		this.bizId = bizId;
	}

	public Integer getBizType() {
		return bizType;
	}

	public void setBizType(Integer bizType) {
		this.bizType = bizType;
	}
    
    
}
   