package com.idcq.appserver.dto.programconfig;

import java.io.Serializable;

public class ProgramConfigDto implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4327314559015000163L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_program_config.program_config_id
     *
     * @mbggenerated Mon Mar 14 19:12:34 CST 2016
     */
    private Integer programConfigId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_program_config.spring_bean
     *
     * @mbggenerated Mon Mar 14 19:12:34 CST 2016
     */
    private String springBean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_program_config.program_interface
     *
     * @mbggenerated Mon Mar 14 19:12:34 CST 2016
     */
    private String programInterface;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_program_config.module_code
     *
     * @mbggenerated Mon Mar 14 19:12:34 CST 2016
     */
    private String moduleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_program_config.program_code
     *
     * @mbggenerated Mon Mar 14 19:12:34 CST 2016
     */
    private String programCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_program_config.program_type
     *
     * @mbggenerated Mon Mar 14 19:12:34 CST 2016
     */
    private Integer programType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_program_config.program_name
     *
     * @mbggenerated Mon Mar 14 19:12:34 CST 2016
     */
    private String programName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_program_config.program_desc
     *
     * @mbggenerated Mon Mar 14 19:12:34 CST 2016
     */
    private String programDesc;

	public ProgramConfigDto() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Integer getProgramConfigId() {
		return programConfigId;
	}

	public void setProgramConfigId(Integer programConfigId) {
		this.programConfigId = programConfigId;
	}

	public String getSpringBean() {
		return springBean;
	}

	public void setSpringBean(String springBean) {
		this.springBean = springBean;
	}

	public String getProgramInterface() {
		return programInterface;
	}

	public void setProgramInterface(String programInterface) {
		this.programInterface = programInterface;
	}

	public String getModuleCode() {
		return moduleCode;
	}

	public void setModuleCode(String moduleCode) {
		this.moduleCode = moduleCode;
	}

	public String getProgramCode() {
		return programCode;
	}

	public void setProgramCode(String programCode) {
		this.programCode = programCode;
	}

	public Integer getProgramType() {
		return programType;
	}

	public void setProgramType(Integer programType) {
		this.programType = programType;
	}

	public String getProgramName() {
		return programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	public String getProgramDesc() {
		return programDesc;
	}

	public void setProgramDesc(String programDesc) {
		this.programDesc = programDesc;
	}
    
    

}