package com.idcq.appserver.dto.activity;

import java.io.Serializable;
import java.util.Date;

public class ActivityModelConfigDto implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5293461357221545495L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_activity_model_config.config_id
     *
     * @mbggenerated Sat Mar 12 12:24:33 CST 2016
     */
    private Integer configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_activity_model_config.model_id
     *
     * @mbggenerated Sat Mar 12 12:24:33 CST 2016
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_activity_model_config.config_type
     *
     * @mbggenerated Sat Mar 12 12:24:33 CST 2016
     */
    private Integer configType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_activity_model_config.config_value
     *
     * @mbggenerated Sat Mar 12 12:24:33 CST 2016
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_activity_model_config.config_code
     *
     * @mbggenerated Sat Mar 12 12:24:33 CST 2016
     */
    private String configCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_activity_model_config.config_name
     *
     * @mbggenerated Sat Mar 12 12:24:33 CST 2016
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_activity_model_config.config_desc
     *
     * @mbggenerated Sat Mar 12 12:24:33 CST 2016
     */
    private String configDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_activity_model_config.create_time
     *
     * @mbggenerated Sat Mar 12 12:24:33 CST 2016
     */
    private Date createTime;

	public ActivityModelConfigDto() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Integer getConfigId() {
		return configId;
	}

	public void setConfigId(Integer configId) {
		this.configId = configId;
	}

	public Integer getModelId() {
		return modelId;
	}

	public void setModelId(Integer modelId) {
		this.modelId = modelId;
	}

	public Integer getConfigType() {
		return configType;
	}

	public void setConfigType(Integer configType) {
		this.configType = configType;
	}

	public String getConfigValue() {
		return configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

	public String getConfigCode() {
		return configCode;
	}

	public void setConfigCode(String configCode) {
		this.configCode = configCode;
	}

	public String getConfigName() {
		return configName;
	}

	public void setConfigName(String configName) {
		this.configName = configName;
	}

	public String getConfigDesc() {
		return configDesc;
	}

	public void setConfigDesc(String configDesc) {
		this.configDesc = configDesc;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		return "ActivityModelConfigDto [configId=" + configId + ", modelId="
				+ modelId + ", configType=" + configType + ", configValue="
				+ configValue + ", configCode=" + configCode + ", configName="
				+ configName + ", configDesc=" + configDesc + ", createTime="
				+ createTime + "]";
	}
    
    

}