package com.idcq.appserver.dto.activity;

import java.io.Serializable;

public class BusinessAreaUserDto extends BusinessAreaUserKeyDto implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -7345918668208688402L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_user.user_id
     *
     * @mbggenerated Sat Mar 12 13:31:30 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_user.mobile
     *
     * @mbggenerated Sat Mar 12 13:31:30 CST 2016
     */
    private Long mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_user.shop_id
     *
     * @mbggenerated Sat Mar 12 13:31:30 CST 2016
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_user.user_source_type
     *
     * @mbggenerated Sat Mar 12 13:31:30 CST 2016
     */
    private Integer userSourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_user.get_source_type
     *
     * @mbggenerated Sat Mar 12 13:31:30 CST 2016
     */
    private Integer getSourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_user.order_num
     *
     * @mbggenerated Sat Mar 12 13:31:30 CST 2016
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_user.client_system_type
     *
     * @mbggenerated Sat Mar 12 13:31:30 CST 2016
     */
    private Integer clientSystemType;

	public BusinessAreaUserDto() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getMobile() {
		return mobile;
	}

	public void setMobile(Long mobile) {
		this.mobile = mobile;
	}

	public Long getShopId() {
		return shopId;
	}

	public void setShopId(Long shopId) {
		this.shopId = shopId;
	}

	public Integer getUserSourceType() {
		return userSourceType;
	}

	public void setUserSourceType(Integer userSourceType) {
		this.userSourceType = userSourceType;
	}

	public Integer getGetSourceType() {
		return getSourceType;
	}

	public void setGetSourceType(Integer getSourceType) {
		this.getSourceType = getSourceType;
	}

	public Integer getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Integer getClientSystemType() {
		return clientSystemType;
	}

	public void setClientSystemType(Integer clientSystemType) {
		this.clientSystemType = clientSystemType;
	}

	@Override
	public String toString() {
		return "BusinessAreaUserDto [userId=" + userId + ", mobile=" + mobile
				+ ", shopId=" + shopId + ", userSourceType=" + userSourceType
				+ ", getSourceType=" + getSourceType + ", orderNum=" + orderNum
				+ ", clientSystemType=" + clientSystemType + "]";
	}
    
    
    

}