package com.idcq.appserver.dto.activity;

import java.io.Serializable;
import java.util.Date;

public class BusinessAreaModelDto implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1077494679766814332L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_model.model_id
     *
     * @mbggenerated Sat Mar 12 11:57:35 CST 2016
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_model.model_name
     *
     * @mbggenerated Sat Mar 12 11:57:35 CST 2016
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_model.model_desc
     *
     * @mbggenerated Sat Mar 12 11:57:35 CST 2016
     */
    private String modelDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_model.activity_desc_model
     *
     * @mbggenerated Sat Mar 12 11:57:35 CST 2016
     */
    private String activityDescModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_model.activity_protocol_model
     *
     * @mbggenerated Sat Mar 12 11:57:35 CST 2016
     */
    private String activityProtocolModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_model.activity_title_model
     *
     * @mbggenerated Sat Mar 12 11:57:35 CST 2016
     */
    private String activityTitleModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_model.activity_share_title_model
     *
     * @mbggenerated Sat Mar 12 11:57:35 CST 2016
     */
    private String activityShareTitleModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_model.valid_day
     *
     * @mbggenerated Sat Mar 12 11:57:35 CST 2016
     */
    private Integer validDay;

    
    private String activityRuleModle;
    public String getActivityRuleModle() {
		return activityRuleModle;
	}

	public void setActivityRuleModle(String activityRuleModle) {
		this.activityRuleModle = activityRuleModle;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_model.create_time
     *
     * @mbggenerated Sat Mar 12 11:57:35 CST 2016
     */
    private Date createTime;

	public BusinessAreaModelDto() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Integer getModelId() {
		return modelId;
	}

	public void setModelId(Integer modelId) {
		this.modelId = modelId;
	}

	public String getModelName() {
		return modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	public String getModelDesc() {
		return modelDesc;
	}

	public void setModelDesc(String modelDesc) {
		this.modelDesc = modelDesc;
	}

	public String getActivityDescModel() {
		return activityDescModel;
	}

	public void setActivityDescModel(String activityDescModel) {
		this.activityDescModel = activityDescModel;
	}

	public String getActivityProtocolModel() {
		return activityProtocolModel;
	}

	public void setActivityProtocolModel(String activityProtocolModel) {
		this.activityProtocolModel = activityProtocolModel;
	}

	public String getActivityTitleModel() {
		return activityTitleModel;
	}

	public void setActivityTitleModel(String activityTitleModel) {
		this.activityTitleModel = activityTitleModel;
	}

	public String getActivityShareTitleModel() {
		return activityShareTitleModel;
	}

	public void setActivityShareTitleModel(String activityShareTitleModel) {
		this.activityShareTitleModel = activityShareTitleModel;
	}

	public Integer getValidDay() {
		return validDay;
	}

	public void setValidDay(Integer validDay) {
		this.validDay = validDay;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		return "BusinessAreaModelDto [modelId=" + modelId + ", modelName="
				+ modelName + ", modelDesc=" + modelDesc
				+ ", activityDescModel=" + activityDescModel
				+ ", activityProtocolModel=" + activityProtocolModel
				+ ", activityTitleModel=" + activityTitleModel
				+ ", activityShareTitleModel=" + activityShareTitleModel
				+ ", validDay=" + validDay + ", createTime=" + createTime + "]";
	}

    
    
}