package com.idcq.appserver.dto.activity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class BusinessAreaShopDto extends BusinessAreaShopKeyDto implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4998517226120168426L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.shop_type
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Integer shopType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.status
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.member_num
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Integer memberNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.redpacket_order_num
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Integer redpacketOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.redpacket_used_num
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Integer redpacketUsedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.redpacket_used_money
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Double redpacketUsedMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.join_time
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Date joinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.join_type
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Integer joinType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.client_system_type
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Integer clientSystemType;

    
    private List<Long>activityIdList;
    
    private Long cityId;
    
    private Integer activityStatus;
	public BusinessAreaShopDto() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Integer getShopType() {
		return shopType;
	}

	public void setShopType(Integer shopType) {
		this.shopType = shopType;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getMemberNum() {
		return memberNum;
	}

	public void setMemberNum(Integer memberNum) {
		this.memberNum = memberNum;
	}

	public Integer getRedpacketOrderNum() {
		return redpacketOrderNum;
	}

	public void setRedpacketOrderNum(Integer redpacketOrderNum) {
		this.redpacketOrderNum = redpacketOrderNum;
	}

	public Integer getRedpacketUsedNum() {
		return redpacketUsedNum;
	}

	public void setRedpacketUsedNum(Integer redpacketUsedNum) {
		this.redpacketUsedNum = redpacketUsedNum;
	}

	public Double getRedpacketUsedMoney() {
		return redpacketUsedMoney;
	}

	public void setRedpacketUsedMoney(Double redpacketUsedMoney) {
		this.redpacketUsedMoney = redpacketUsedMoney;
	}

	public Date getJoinTime() {
		return joinTime;
	}

	public void setJoinTime(Date joinTime) {
		this.joinTime = joinTime;
	}

	public Integer getJoinType() {
		return joinType;
	}

	public void setJoinType(Integer joinType) {
		this.joinType = joinType;
	}

	public Integer getClientSystemType() {
		return clientSystemType;
	}

	public void setClientSystemType(Integer clientSystemType) {
		this.clientSystemType = clientSystemType;
	}

	@Override
	public String toString() {
		return "BusinessAreaShopDto [shopType=" + shopType + ", status="
				+ status + ", memberNum=" + memberNum + ", redpacketOrderNum="
				+ redpacketOrderNum + ", redpacketUsedNum=" + redpacketUsedNum
				+ ", redpacketUsedMoney=" + redpacketUsedMoney + ", joinTime="
				+ joinTime + ", joinType=" + joinType + ", clientSystemType="
				+ clientSystemType + "]";
	}

	public List<Long> getActivityIdList() {
		return activityIdList;
	}

	public void setActivityIdList(List<Long> activityIdList) {
		this.activityIdList = activityIdList;
	}

	public Long getCityId() {
		return cityId;
	}

	public void setCityId(Long cityId) {
		this.cityId = cityId;
	}

	public Integer getActivityStatus() {
		return activityStatus;
	}

	public void setActivityStatus(Integer activityStatus) {
		this.activityStatus = activityStatus;
	}

    
}