package com.idcq.appserver.dto.activity;


public class BusinessAreaStatDto extends BusinessAreaStatKeyDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.member_num
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Integer memberNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.send_num
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Integer sendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.total_money
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Double totalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.real_money
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Double realMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.order_num
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.order_money
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Double orderMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.send_redpacket_num
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Integer sendRedpacketNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.send_redpacket_money
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Double sendRedpacketMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.used_redpacket_num
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Integer usedRedpacketNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.used_redpacket_money
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Double usedRedpacketMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.share_num
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Integer shareNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.read_num
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_stat.transmit_num
     *
     * @mbggenerated Sat Mar 12 12:07:08 CST 2016
     */
    private Integer transmitNum;

	public BusinessAreaStatDto() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Integer getMemberNum() {
		return memberNum;
	}

	public void setMemberNum(Integer memberNum) {
		this.memberNum = memberNum;
	}

	public Integer getSendNum() {
		return sendNum;
	}

	public void setSendNum(Integer sendNum) {
		this.sendNum = sendNum;
	}

	public Double getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(Double totalMoney) {
		this.totalMoney = totalMoney;
	}

	public Double getRealMoney() {
		return realMoney;
	}

	public void setRealMoney(Double realMoney) {
		this.realMoney = realMoney;
	}

	public Integer getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Double getOrderMoney() {
		return orderMoney;
	}

	public void setOrderMoney(Double orderMoney) {
		this.orderMoney = orderMoney;
	}

	public Integer getSendRedpacketNum() {
		return sendRedpacketNum;
	}

	public void setSendRedpacketNum(Integer sendRedpacketNum) {
		this.sendRedpacketNum = sendRedpacketNum;
	}

	public Double getSendRedpacketMoney() {
		return sendRedpacketMoney;
	}

	public void setSendRedpacketMoney(Double sendRedpacketMoney) {
		this.sendRedpacketMoney = sendRedpacketMoney;
	}

	public Integer getUsedRedpacketNum() {
		return usedRedpacketNum;
	}

	public void setUsedRedpacketNum(Integer usedRedpacketNum) {
		this.usedRedpacketNum = usedRedpacketNum;
	}

	public Double getUsedRedpacketMoney() {
		return usedRedpacketMoney;
	}

	public void setUsedRedpacketMoney(Double usedRedpacketMoney) {
		this.usedRedpacketMoney = usedRedpacketMoney;
	}

	public Integer getShareNum() {
		return shareNum;
	}

	public void setShareNum(Integer shareNum) {
		this.shareNum = shareNum;
	}

	public Integer getReadNum() {
		return readNum;
	}

	public void setReadNum(Integer readNum) {
		this.readNum = readNum;
	}

	public Integer getTransmitNum() {
		return transmitNum;
	}

	public void setTransmitNum(Integer transmitNum) {
		this.transmitNum = transmitNum;
	}

	@Override
	public String toString() {
		return "BusinessAreaStatDto [memberNum=" + memberNum + ", sendNum="
				+ sendNum + ", totalMoney=" + totalMoney + ", realMoney="
				+ realMoney + ", orderNum=" + orderNum + ", orderMoney="
				+ orderMoney + ", sendRedpacketNum=" + sendRedpacketNum
				+ ", sendRedpacketMoney=" + sendRedpacketMoney
				+ ", usedRedpacketNum=" + usedRedpacketNum
				+ ", usedRedpacketMoney=" + usedRedpacketMoney + ", shareNum="
				+ shareNum + ", readNum=" + readNum + ", transmitNum="
				+ transmitNum + "]";
	}
    
    
    

}