package com.idcq.appserver.dto.activity;

public class BusinessAreaShopKeyDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.business_area_activity_id
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Long businessAreaActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1dcq_business_area_shop.shop_id
     *
     * @mbggenerated Sat Mar 12 12:05:17 CST 2016
     */
    private Long shopId;

	public Long getBusinessAreaActivityId() {
		return businessAreaActivityId;
	}

	public void setBusinessAreaActivityId(Long businessAreaActivityId) {
		this.businessAreaActivityId = businessAreaActivityId;
	}

	public Long getShopId() {
		return shopId;
	}

	public void setShopId(Long shopId) {
		this.shopId = shopId;
	}

   
}